socialmedia_index:
    path:     /
    defaults: { _controller: "AppBundle:SocialMedia:index" }
    methods:  GET

socialmedia_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:SocialMedia:show" }
    methods:  GET

socialmedia_new:
    path:     /new
    defaults: { _controller: "AppBundle:SocialMedia:new" }
    methods:  [GET, POST]

socialmedia_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:SocialMedia:edit" }
    methods:  [GET, POST]

socialmedia_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:SocialMedia:delete" }
    methods:  DELETE
