user_index:
    path:     /
    defaults: { _controller: "AppBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:User:show" }
    methods:  GET

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:User:delete" }
    methods:  DELETE

user_recruit:
    path:     /recruit/{gameId}
    defaults: { _controller: "AppBundle:User:recruit" }
    methods:  GET