user_index:
    path:     /
    defaults: { _controller: "AppBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:User:show" }
    methods:  GET

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:User:delete" }
    methods:  GET

user_recruit:
    path:     /recruit/{gameId}
    defaults: { _controller: "AppBundle:User:recruit" }
    methods:  GET

user_validate:
    path:     /validate/{id}/{status}
    defaults: { _controller: "AppBundle:User:validate" }
    methods:  GET
    
user_payed:
    path:     /payed/{id}/
    defaults: { _controller: "AppBundle:User:payedUser" }
    methods:  GET

user_confirm:
    path:     /confirm/{id}/
    defaults: { _controller: "AppBundle:User:confirmationUser" }
    methods:  GET

labeli_by_payed:
    path:     /by_payed/{state}
    defaults: { _controller: "AppBundle:User:byPayed" }
    methods:  GET

user_check_labeli:
    path:     /check_labeli
    defaults: { _controller: "AppBundle:User:checkIfLabeli" }
    methods:  GET

user_by_labeli:
    path:     /by_labeli
    defaults: { _controller: "AppBundle:User:byLabeli" }
    methods:  GET