app_category:
    resource: "@AppBundle/Resources/config/routing/category.yml"
    prefix:   /category

app_game:
    resource: "@AppBundle/Resources/config/routing/game.yml"
    prefix:   /game

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user

app_organizer:
    resource: "@AppBundle/Resources/config/routing/organizer.yml"
    prefix:   /organizer

app_socialmedia:
    resource: "@AppBundle/Resources/config/routing/socialmedia.yml"
    prefix:   /socialmedia

app_player:
    resource: "@AppBundle/Resources/config/routing/player.yml"
    prefix:   /player

app_application:
    resource: "@AppBundle/Resources/config/routing/application.yml"
    prefix:   /application
    
app_team:
    resource: "@AppBundle/Resources/config/routing/team.yml"
    prefix:   /team

labelilan:
    path:     /
    defaults: { _controller: AppBundle:Default:accueil }
    
informations:
    path:     /informations
    defaults: { _controller: AppBundle:Default:informations }