app_category:
    resource: "@AppBundle/Resources/config/routing/category.yml"
    prefix:   /category

app_game:
    resource: "@AppBundle/Resources/config/routing/game.yml"
    prefix:   /game

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user

app_organizer:
    resource: "@AppBundle/Resources/config/routing/organizer.yml"
    prefix:   /organizer

app_socialmedia:
    resource: "@AppBundle/Resources/config/routing/socialmedia.yml"
    prefix:   /socialmedia



labelilan:
    path:     /
    defaults: { _controller: AppBundle:Default:accueil }
    
informations:
    path:     /informations
    defaults: { _controller: AppBundle:Default:informations }