app_ordering:
    resource: "@AppBundle/Resources/config/routing/ordering.yml"
    prefix:   /ordering

app_pizza:
    resource: "@AppBundle/Resources/config/routing/pizza.yml"
    prefix:   /pizza

app_labeli:
    resource: "@AppBundle/Resources/config/routing/labeli.yml"
    prefix:   /labeli

app_category:
    resource: "@AppBundle/Resources/config/routing/category.yml"
    prefix:   /category

app_game:
    resource: "@AppBundle/Resources/config/routing/game.yml"
    prefix:   /game

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user

app_organizer:
    resource: "@AppBundle/Resources/config/routing/organizer.yml"
    prefix:   /organizer

app_socialmedia:
    resource: "@AppBundle/Resources/config/routing/socialmedia.yml"
    prefix:   /socialmedia

app_player:
    resource: "@AppBundle/Resources/config/routing/player.yml"
    prefix:   /player

app_application:
    resource: "@AppBundle/Resources/config/routing/application.yml"
    prefix:   /application
    
app_team:
    resource: "@AppBundle/Resources/config/routing/team.yml"
    prefix:   /team
    
app_partner:
    resource: "@AppBundle/Resources/config/routing/partner.yml"
    prefix:   /partner

labelilan:
    path:     /
    defaults: { _controller: AppBundle:Default:accueil }
    requirements:
        _method:  GET

informations:
    path:     /informations
    defaults: { _controller: AppBundle:Default:informations }
    
dlreglement:
    path:     /downloadReglementPdf
    defaults: { _controller: AppBundle:Default:downloadReglementPdf }
    
dlDroitImage:
    path:     /downloadDroitImage
    defaults: { _controller: AppBundle:Default:downloadDroitImage }
    
dlDroitImageMineur:
    path:     /downloadDroitImageMineur
    defaults: { _controller: AppBundle:Default:downloadDroitImageMineur }
    
dlAccordParental:
    path:     /downloadAccordParental
    defaults: { _controller: AppBundle:Default:downloadAccordParental }
    
dlpokemon_inscription:
    path:     /download_pokemon_inscription
    defaults: { _controller: AppBundle:Default:downloadPokemon }
    
mentions_legales:
    path:     /mentions_legales
    defaults: { _controller: AppBundle:Default:downloadReglementPdf }

lost_password:
    path:     /lost_password/
    defaults: { _controller: AppBundle:Default:lostPassword}
    
    