AppBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        systName:
            type: string
            length: 255
            column: syst_name
    lifecycleCallbacks: {  }
    
    oneToMany:
        game:
            targetEntity: Game
            mappedBy: category
            cascade: [ "remove", "persist" ]
