AppBundle\Entity\Game:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GameRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        systName:
            type: string
            length: 255
            column: syst_name
        description:
            type: string
            length: 2000
        places:
            type: integer
            nullable: true
        nbplayers:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
    
 #   oneToOne:
 #       image:
 #           targetEntity:             Image
 #           cascade:                  [ remove, persist ]
 #           joinColumn:
 #               name:                 image_id
 #               referencedColumnName: id
 #               onDelete:             CASCADE
    oneToMany:
        player:
            targetEntity:             Player
            mappedBy:                 game
            cascade:                  [ "remove", "persist" ]
        team:
            targetEntity:             Team
            mappedBy:                 game
            cascade:                  [ "remove", "persist" ]
    manyToOne:
        category:
            targetEntity:             Category
            cascade:                  [ persist ]
            inversedBy:               game
            joinColumn:
                name:                 category_id
                referencedColumnName: id
                onDelete:             CASCADE
        organizer:
            targetEntity:             Organizer
            cascade:                  [ persist ]
            inversedBy:               game
            joinColumn:
                name:                 organizer_id
                referencedColumnName: id
                onDelete:             CASCADE
