AppBundle\Entity\Organizer:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\OrganizerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        systName:
            type: string
            length: 255
        description:
            type: string
            length: 500
    lifecycleCallbacks: {  }
    
    oneToMany:
        game:
            targetEntity: Game
            mappedBy: organizer
            cascade: [ remove, persist ]
        socialMedia:
            targetEntity: SocialMedia
            mappedBy: organizer
            cascade: [ remove, persist ]


