AppBundle\Entity\Partner:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PartnerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        systName:
            type: string
            length: 255
        description:
            type: string
            length: '500'
            nullable: true
    lifecycleCallbacks: {  }

    oneToMany:
        socialMedia:
            targetEntity: SocialMedia
            mappedBy: partner
            cascade: [ remove, persist ]