AppBundle\Entity\Player:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PlayerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pseudo:
            type: string
            length: 255
            nullable: true
        capitain:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }

    manyToOne:
        game:
            targetEntity:             Game
            cascade:                  [ persist ]
            joinColumn:
                name:                 game_id
                referencedColumnName: id
                onDelete:             CASCADE
        user:
            targetEntity:             User
            cascade:                  [ persist ]
            joinColumn:
                name:                 user_id
                referencedColumnName: id
                onDelete:             CASCADE
        team:
            targetEntity:             Team
            cascade:                  [ persist ]
            joinColumn:
                name:                 team_id
                referencedColumnName: id
                onDelete:             CASCADE