AppBundle\Entity\SocialMedia:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SocialMediaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        link:
            type: string
            length: 255
        icon:
            type: string
            length: 255
    lifecycleCallbacks: {  }

    manyToOne:
        organizer:
            targetEntity:             Organizer
            cascade:                  [ persist ]
            inversedBy:               socialMedia
            joinColumn:
                name:                 organizer_id
                referencedColumnName: id
                onDelete:             CASCADE
        partner:
            targetEntity:             Partner
            cascade:                  [ persist ]
            inversedBy:               socialMedia
            joinColumn:
                name:                 partner_id
                referencedColumnName: id
                onDelete:             CASCADE