AppBundle\Entity\Team:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TeamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        validation:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }

    oneToMany:
        player:
            targetEntity: Player
            mappedBy: team
        application:
            targetEntity: Application
            mappedBy: team
            
    manyToOne:
        game:
            targetEntity:             Game
            cascade:                  [ persist ]
            inversedBy:               team
            joinColumn:
                name:                 game_id
                referencedColumnName: id
                onDelete:             CASCADE