AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        dateNaissance:
            type: date
        payed:
            type: boolean
            nullable: true
    
    oneToMany:
        player:
            targetEntity: Player
            mappedBy: user
        application:
            targetEntity: Application
            mappedBy: user
